apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: asset-provider
  labels:
    name: asset-provider
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: asset-provider
    spec:
      containers:
      - name: asset-provider
        image: gcr.io/$GCP_PROJECT/asset-provider:latest
        ports:
          - containerPort: 22
        volumeMounts:
          - name: certificates-volume
            mountPath: "/etc/letsencrypt/"
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
      volumes:
        - name: docker-sock
          hostPath:
              path: /var/run/docker.sock
        - name: certificates-volume
          gcePersistentDisk:
            pdName: application-certificates # This should be the name on an already created GCP's Compute Engine Disk
            fsType: ext4
