apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: asset-provider
  labels:
    name: asset-provider
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: asset-provider
    spec:
      containers:
      - name: asset-provider
        image: gcr.io/cloud-vibes/asset-provider:a60d57535695a5e33f742189051dc5baaaa9e7b0
        ports:
          - containerPort: 22
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
      volumes:
        - name: docker-sock
          hostPath:
              path: /var/run/docker.sock
