apiVersion: v1
kind: Service
metadata:
  labels:
    name: asset-provider
  name: asset-provider
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: asset-provider
